server:
  port: 8081 # HTTP (Tomcat) port

spring:
  application:
    name: customer-handler-api-test-app

  config:
    import: >
      customer-handler-api-test-app.yml,
      webclient.yml,
      swagger-configuration.yml
  cloud:
    config:
      enabled: false

  jackson:
    deserialization:
      accept-single-value-as-array: true
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    com.customer.handling.test.controller: INFO

  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: info, health
